name: Java CI

on: [workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Setup OpenJDK 21
       # uses: actions/setup-java@v2
        #with:
         # java-version: '21-ea'
          #distribution: 'temurin'

      - name: Download Java
        run:
            mkdir server
            cd server
            
            wget https://aka.ms/download-jdk/microsoft-jdk-21.0.4-linux-x64.tar.gz

            tar -xvzf microsoft-jdk-21.0.4-linux-x64.tar.gz 

      - name: Download Server, Mods...
        run:
            wget https://meta.fabricmc.net/v2/versions/loader/1.21/0.15.11/1.0.1/server/jar

            mv jar fabric.jar

            echo "eula=true" >> eula.txt

            wget https://cdn.modrinth.com/data/qANg5Jrr/versions/JwZn7YZ0/e4mc_minecraft-5.1.0.jar
            wget https://cdn.modrinth.com/data/P7dR8mSH/versions/oGwyXeEI/fabric-api-0.102.0%2B1.21.jar

            mkdir mods

            mv e4mc_minecraft-5.1.0.jar mods/
            mv fabric-api-0.102.0+1.21.jar mods/
     
      - name: Run Server
        run:
            ./jdk-21.0.4+7/bin/java -jar fabric.jar

      - name: Saving server files
            run :
                rm fabric.jar
                rm minecraft_server*
                rm -r mods/
                rm eula.txt
                
      - uses: actions/upload-artifact@v4
            with:
                name: server-files
                path: .
