jobs:
  build:
    on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '21' ]

    name: Java ${{ matrix.Java }} sample
    runns-on: [ workflow_dispatch ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: '<distribution>'
          java-version: ${{ matrix.java }}
      - run: java --version
