name: Java CI

on: [workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OpenJDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'openjdk'

      - name: Run JAR file
        run: |
          java --version