name: Java CI

on: [workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Setup OpenJDK 21
       # uses: actions/setup-java@v2
        #with:
         # java-version: '21-ea'
          #distribution: 'temurin'

      - name: Download Java
        run: 
            mkdir minecraft
            
            cd minecraft
            
            wget https://aka.ms/download-jdk/microsoft-jdk-21.0.4-linux-x64.tar.gz 

            tar -xvzf microsoft-jdk-21.0.4-linux-x64.tar.gz

            rm microsoft-jdk-21.0.4-linux-x64.tar.gz

      - name: Download Server, Mods...
        run: 
            cd minecraft
            
            wget https://meta.fabricmc.net/v2/versions/loader/1.21/0.15.11/1.0.1/server/jar 

            mv jar fabric.jar 

            echo "eula=true" >> eula.txt 

            wget https://cdn.modrinth.com/data/qANg5Jrr/versions/JwZn7YZ0/e4mc_minecraft-5.1.0.jar 
            
            wget https://cdn.modrinth.com/data/P7dR8mSH/versions/oGwyXeEI/fabric-api-0.102.0%2B1.21.jar 

            mkdir mods 

            mv e4mc_minecraft-5.1.0.jar mods/ 
            
            mv fabric-api-0.102.0+1.21.jar mods/

      - name: download server data of recent runs
        run:
            runid=$(curl -s https://github.com/Farmer-Markus/testrepo/actions/workflows/server.yml | grep -oE 'runs/[0-9]+' | head -1 | cut -d '/' -f2)

            artifactid=$(curl -s https://api.github.com/repos/Farmer-Markus/testrepo/actions/runs/10334008188/artifacts | head -n 9 | tail -n 1 | grep -oE '[0-9]+' | tail -n 1)

            wget https://github.com/Farmer-Markus/testrepo/actions/runs/$runid/artifacts/$artifactid

            unzip server-files.zip

            rm server-files.zip
                  

      - name: Make me op
        if: always()
        run:
            cd minecraft

            echo '[{"uuid":"e19160a6-9f06-4c6e-b7bc-66c9f4121453", "name":"Farmer_Markus", "level":4, "bypassesPlayerLimit":false}]' >> ops.json

      - name: Run Server
        run:
            cd minecraft
            
            ./jdk-21.0.4+7/bin/java -jar fabric.jar

     # - name: Saving server files
           # run :
            #    rm fabric.jar
            #    rm minecraft_server*
            #    rm -r mods/
           #     rm eula.txt
                
      - uses: actions/upload-artifact@v4
        with:
                name: server-files
                path: minecraft/
